interface testData {
  name: string;
  lastName: string;
  Date: string;
  rank: string;
}

export const testData: testData[] = [
  {
    name: "محمد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "علی",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "رضا",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "کیان",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "فربد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "محمد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "علی",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "رضا",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "کیان",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "فربد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "محمد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "علی",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "رضا",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "کیان",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "فربد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "محمد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "علی",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "رضا",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "کیان",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "فربد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "محمد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "علی",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "رضا",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "کیان",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "فربد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "محمد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "علی",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "رضا",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "کیان",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "فربد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "محمد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "علی",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "رضا",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "کیان",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "فربد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "محمد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "علی",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "رضا",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "کیان",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "ادمین",
  },
  {
    name: "فربد",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
  {
    name: "حسام",
    lastName: "فلانی",
    Date: "20/20/2020",
    rank: "عضو",
  },
];
